/*-
 * Copyright (c) 2017 Taketsuru <taketsuru11@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#pragma once

#ifndef _KERNEL
#error This file is not for userland code.
#endif

enum {
	KHTTPD_METHOD_UNKNOWN = -1,

	KHTTPD_METHOD_ACL,
	KHTTPD_METHOD_BASELINE_CONTROL,
	KHTTPD_METHOD_BIND,
	KHTTPD_METHOD_CHECKIN,
	KHTTPD_METHOD_CHECKOUT,
	KHTTPD_METHOD_CONNECT,
	KHTTPD_METHOD_COPY,
	KHTTPD_METHOD_DELETE,
	KHTTPD_METHOD_GET,
	KHTTPD_METHOD_HEAD,
	KHTTPD_METHOD_LABEL,
	KHTTPD_METHOD_LINK,
	KHTTPD_METHOD_LOCK,
	KHTTPD_METHOD_MERGE,
	KHTTPD_METHOD_MKACTIVITY,
	KHTTPD_METHOD_MKCALENDAR,
	KHTTPD_METHOD_MKCOL,
	KHTTPD_METHOD_MKREDIRECTREF,
	KHTTPD_METHOD_MKWORKSPACE,
	KHTTPD_METHOD_MOVE,
	KHTTPD_METHOD_OPTIONS,
	KHTTPD_METHOD_ORDERPATCH,
	KHTTPD_METHOD_PATCH,
	KHTTPD_METHOD_POST,
	KHTTPD_METHOD_PRI,
	KHTTPD_METHOD_PROPFIND,
	KHTTPD_METHOD_PROPPATCH,
	KHTTPD_METHOD_PUT,
	KHTTPD_METHOD_REBIND,
	KHTTPD_METHOD_REPORT,
	KHTTPD_METHOD_SEARCH,
	KHTTPD_METHOD_TRACE,
	KHTTPD_METHOD_UNBIND,
	KHTTPD_METHOD_UNCHECKOUT,
	KHTTPD_METHOD_UNLINK,
	KHTTPD_METHOD_UNLOCK,
	KHTTPD_METHOD_UPDATE,
	KHTTPD_METHOD_UPDATEREDIRECTREF,
	KHTTPD_METHOD_VERSION_CONTROL,

	KHTTPD_METHOD_END
};

int khttpd_method_find(const char *begin, const char *end);
const char *khttpd_method_name(int method);
