#!/bin/sh
# \
exec tclsh8.7 "$0" ${1+"$@"}

package require itcl

itcl::class testsuite {
    variable	pkgname
}

itcl::class testcase {
    variable	testsuite
    variable	name
    variable	testcode

    protected constructor {ts tcode} {
	set testsuite $ts
	set testcode [itcl::code $tcode]
    }

    public method run {ctx} {
	setup
	test
	teardown
    }

    protected method test {} {
	puts "test!"
    }

    protected method setup {} {
	puts "setup!"
    }

    protected method teardown {} {
	puts "teardown!"
    }
}

testsuite khttpd_fcgi

itcl::class khttpd_testcase {
    inherit testcase

    
}

testcase fcgi_basic khttpd_fcgi {
}
