/*-
 * Copyright (c) 2015 Taketsuru <taketsuru11@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.	IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

(function () {
    var app = angular.module('sysUi', []);

    app.controller('sysctlPanelController', function () {
	this.sysctl = {};
	this.sysctl.items = [
	    {"href":"/sys/sysctl/1.1",
	     "name":"kern.ostype",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.2",
	     "name":"kern.osrelease",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.3",
	     "name":"kern.osrevision",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.4",
	     "name":"kern.version",
	     "flags":["rd", "mpsafe"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.5",
	     "name":"kern.maxvnodes",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.6",
	     "name":"kern.maxproc",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7",
	     "name":"kern.maxfiles",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.8",
	     "name":"kern.argmax",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.9",
	     "name":"kern.securelevel",
	     "flags":["rd", "wr", "prison"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.a",
	     "name":"kern.hostname",
	     "flags":["rd", "wr", "prison", "mpsafe"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.b",
	     "name":"kern.hostid",
	     "flags":["rd", "wr", "prison", "mpsafe"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.c",
	     "name":"kern.clockrate",
	     "flags":["rd", "mpsafe"],
	     "type":"opaque",
	     "format":"S,clockinfo" },
	    {"href":"/sys/sysctl/1.e.0",
	     "name":"kern.proc.all",
	     "flags":["rd", "mpsafe"],
	     "type":"opaque",
	     "format":"S,proc" },
	    {"href":"/sys/sysctl/1.e.1",
	     "name":"kern.proc.pid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.2",
	     "name":"kern.proc.pgrp",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.3",
	     "name":"kern.proc.sid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.4",
	     "name":"kern.proc.tty",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.5",
	     "name":"kern.proc.uid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.6",
	     "name":"kern.proc.ruid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.7",
	     "name":"kern.proc.args",
	     "flags":["rd", "wr", "anybody", "mpsafe", "capwr"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.8",
	     "name":"kern.proc.proc",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.9",
	     "name":"kern.proc.sv_name",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.a",
	     "name":"kern.proc.rgid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.b",
	     "name":"kern.proc.gid",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.c",
	     "name":"kern.proc.pathname",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.d",
	     "name":"kern.proc.ovmmap",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.e",
	     "name":"kern.proc.ofiledesc",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.f",
	     "name":"kern.proc.kstack",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.11",
	     "name":"kern.proc.pid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.12",
	     "name":"kern.proc.pgrp_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.13",
	     "name":"kern.proc.sid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.14",
	     "name":"kern.proc.tty_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.15",
	     "name":"kern.proc.uid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.16",
	     "name":"kern.proc.ruid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.18",
	     "name":"kern.proc.proc_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.1a",
	     "name":"kern.proc.rgid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.1b",
	     "name":"kern.proc.gid_td",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.20",
	     "name":"kern.proc.vmmap",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.21",
	     "name":"kern.proc.filedesc",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.22",
	     "name":"kern.proc.groups",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.23",
	     "name":"kern.proc.env",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.24",
	     "name":"kern.proc.auxv",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.25",
	     "name":"kern.proc.rlimit",
	     "flags":["rd", "wr", "anybody", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.26",
	     "name":"kern.proc.ps_strings",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.27",
	     "name":"kern.proc.umask",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.28",
	     "name":"kern.proc.osrel",
	     "flags":["rd", "wr", "anybody", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.29",
	     "name":"kern.proc.sigtramp",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.2a",
	     "name":"kern.proc.cwd",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.e.2b",
	     "name":"kern.proc.nfds",
	     "flags":["rd", "mpsafe"],
	     "type":"node",
	     "format":"N" },
	    {"href":"/sys/sysctl/1.f",
	     "name":"kern.file",
	     "flags":["rd", "mpsafe"],
	     "type":"opaque",
	     "format":"S,xfile" },
	    {"href":"/sys/sysctl/1.11",
	     "name":"kern.posix1version",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.12",
	     "name":"kern.ngroups",
	     "flags":["rd", "tun", "mpsafe", "caprd", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.13",
	     "name":"kern.job_control",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.14",
	     "name":"kern.saved_ids",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.15",
	     "name":"kern.boottime",
	     "flags":["rd"],
	     "type":"opaque",
	     "format":"S,timeval" },
	    {"href":"/sys/sysctl/1.16",
	     "name":"kern.domainname",
	     "flags":["rd", "wr", "prison", "mpsafe"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.18",
	     "name":"kern.osreldate",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1a",
	     "name":"kern.bootfile",
	     "flags":["rd", "wr"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.1b",
	     "name":"kern.maxfilesperproc",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1c",
	     "name":"kern.maxprocperuid",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.1",
	     "name":"kern.ipc.maxsockbuf",
	     "flags":["rd", "wr"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.2",
	     "name":"kern.ipc.sockbuf_waste_factor",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.4",
	     "name":"kern.ipc.max_linkhdr",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.5",
	     "name":"kern.ipc.max_protohdr",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.6",
	     "name":"kern.ipc.max_hdr",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7",
	     "name":"kern.ipc.max_datalen",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc46",
	     "name":"kern.ipc.sfstat",
	     "flags":["rd", "wr"],
	     "type":"opaque",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc48.7ffffc47",
	     "name":"kern.ipc.sendfile.readahead",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc49",
	     "name":"kern.ipc.maxsockets",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc4a",
	     "name":"kern.ipc.numopensockets",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc4b",
	     "name":"kern.ipc.soacceptqueue",
	     "flags":["rd", "wr"],
	     "type":"uint",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc53",
	     "name":"kern.ipc.shmsegs",
	     "flags":["rd", "mpsafe"],
	     "type":"opaque",
	     "format":"" },
	    {"href":"/sys/sysctl/1.1e.7ffffc54",
	     "name":"kern.ipc.shm_allow_removed",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc55",
	     "name":"kern.ipc.shm_use_phys",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc56",
	     "name":"kern.ipc.shmall",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc57",
	     "name":"kern.ipc.shmseg",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc58",
	     "name":"kern.ipc.shmmni",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc59",
	     "name":"kern.ipc.shmmin",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc5a",
	     "name":"kern.ipc.shmmax",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.1e.7ffffc5c",
	     "name":"kern.ipc.sema",
	     "flags":["rd"],
	     "type":"opaque",
	     "format":"" },
	    {"href":"/sys/sysctl/1.1e.7ffffc5d",
	     "name":"kern.ipc.semaem",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc5e",
	     "name":"kern.ipc.semvmx",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc5f",
	     "name":"kern.ipc.semusz",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc60",
	     "name":"kern.ipc.semume",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc61",
	     "name":"kern.ipc.semopm",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc62",
	     "name":"kern.ipc.semmsl",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc63",
	     "name":"kern.ipc.semmnu",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc64",
	     "name":"kern.ipc.semmns",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc65",
	     "name":"kern.ipc.semmni",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc67",
	     "name":"kern.ipc.msqids",
	     "flags":["rd"],
	     "type":"opaque",
	     "format":"" },
	    {"href":"/sys/sysctl/1.1e.7ffffc68",
	     "name":"kern.ipc.msgseg",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc69",
	     "name":"kern.ipc.msgssz",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc6a",
	     "name":"kern.ipc.msgtql",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc6b",
	     "name":"kern.ipc.msgmnb",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc6c",
	     "name":"kern.ipc.msgmni",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc6d",
	     "name":"kern.ipc.msgmax",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc70",
	     "name":"kern.ipc.piperesizeallowed",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc71",
	     "name":"kern.ipc.piperesizefail",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc72",
	     "name":"kern.ipc.pipeallocfail",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc73",
	     "name":"kern.ipc.pipefragretry",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.1e.7ffffc74",
	     "name":"kern.ipc.pipekva",
	     "flags":["rd", "mpsafe"],
	     "type":"long",
	     "format":"L" },
	    {"href":"/sys/sysctl/1.1e.7ffffc75",
	     "name":"kern.ipc.maxpipekva",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"long",
	     "format":"L" },
	    {"href":"/sys/sysctl/1.1e.7ffffd3e",
	     "name":"kern.ipc.nmbufs",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffd3f",
	     "name":"kern.ipc.nmbjumbo16",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffd40",
	     "name":"kern.ipc.nmbjumbo9",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffd41",
	     "name":"kern.ipc.nmbjumbop",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffd42",
	     "name":"kern.ipc.nmbclusters",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"IU" },
	    {"href":"/sys/sysctl/1.1e.7ffffd43",
	     "name":"kern.ipc.maxmbufmem",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"s64",
	     "format":"Q" },
	    {"href":"/sys/sysctl/1.1f",
	     "name":"kern.dummy",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.20",
	     "name":"kern.ps_strings",
	     "flags":["rd"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.21",
	     "name":"kern.usrstack",
	     "flags":["rd", "caprd"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.22",
	     "name":"kern.logsigexit",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.23",
	     "name":"kern.iov_max",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.24",
	     "name":"kern.hostuuid",
	     "flags":["rd", "wr", "prison", "mpsafe"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.25",
	     "name":"kern.arandom",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"opaque",
	     "format":"" },
	    {"href":"/sys/sysctl/1.7ffffa99",
	     "name":"kern.crypto_stats",
	     "flags":["rd", "wr"],
	     "type":"opaque",
	     "format":"S,cryptostats" },
	    {"href":"/sys/sysctl/1.7ffffa9a",
	     "name":"kern.cryptodevallowsoft",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffa9b",
	     "name":"kern.userasymcrypto",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffbe2",
	     "name":"kern.minvnodes",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffbe4",
	     "name":"kern.metadelay",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffbe5",
	     "name":"kern.dirdelay",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffbe6",
	     "name":"kern.filedelay",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc4f",
	     "name":"kern.tty_nout",
	     "flags":["rd", "mpsafe"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc50",
	     "name":"kern.tty_nin",
	     "flags":["rd", "mpsafe"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc51",
	     "name":"kern.tty_inq_flush_secure",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc52",
	     "name":"kern.ttys",
	     "flags":["rd", "mpsafe"],
	     "type":"opaque",
	     "format":"S,xtty" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc87",
	     "name":"kern.smp.forward_signal_enabled",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc88",
	     "name":"kern.smp.topology",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc89",
	     "name":"kern.smp.cpus",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc8a",
	     "name":"kern.smp.disabled",
	     "flags":["rd", "tun", "mpsafe", "caprd", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc8b",
	     "name":"kern.smp.active",
	     "flags":["rd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc8c",
	     "name":"kern.smp.maxcpus",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc8e.7ffffc8d",
	     "name":"kern.smp.maxid",
	     "flags":["rd", "mpsafe", "caprd"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc92",
	     "name":"kern.msgbuf_clear",
	     "flags":["rd", "wr", "mpsafe"],
	     "securelevel":0,
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc93",
	     "name":"kern.msgbuf",
	     "flags":["rd", "mpsafe"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.7ffffc95",
	     "name":"kern.always_console_output",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc96",
	     "name":"kern.log_console_add_linefeed",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc97",
	     "name":"kern.log_console_output",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffc98",
	     "name":"kern.vm_guest",
	     "flags":["rd"],
	     "type":"string",
	     "format":"A" },
	    {"href":"/sys/sysctl/1.7ffffc99",
	     "name":"kern.sgrowsiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9a",
	     "name":"kern.maxssiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9b",
	     "name":"kern.dflssiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9c",
	     "name":"kern.maxdsiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9d",
	     "name":"kern.dfldsiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9e",
	     "name":"kern.maxtsiz",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"ulong",
	     "format":"LU" },
	    {"href":"/sys/sysctl/1.7ffffc9f",
	     "name":"kern.bio_transient_maxcnt",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca0",
	     "name":"kern.maxbcache",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"long",
	     "format":"L" },
	    {"href":"/sys/sysctl/1.7ffffca1",
	     "name":"kern.maxswzone",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"long",
	     "format":"L" },
	    {"href":"/sys/sysctl/1.7ffffca2",
	     "name":"kern.msgbufsize",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca3",
	     "name":"kern.nswbuf",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca4",
	     "name":"kern.nbuf",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca5",
	     "name":"kern.hz",
	     "flags":["rd", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca6",
	     "name":"kern.msgbuf_show_timestamp",
	     "flags":["rd", "wr", "tun", "mpsafe", "nofetch"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca7",
	     "name":"kern.log_wakeups_per_second",
	     "flags":["rd", "wr", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffca8",
	     "name":"kern.kobj_methodcount",
	     "flags":["rd", "mpsafe"],
	     "type":"int",
	     "format":"I" },
	    {"href":"/sys/sysctl/1.7ffffcb2",
	     "name":"kern.hintmode",
	     "flags":["rd", "wr"],
	     "type":"int",
	     "format":"I" }
	    ];
	});
})();
