#!/bin/sh

case $1 in
start)
    kldstat -q -n khttpd.ko && kldunload -f khttpd.ko
    kldload modules/khttpd/khttpd.ko
    rm -f exui/access.log exui/error.log
    usr.sbin/khttpd-init/khttpd-init -4 192.168.56.3:8080 \
	-r exui/docroot -l exui/access.log -e exui/error.log 
    ;;

stop)
    kldunload -f khttpd.ko
    ;;
esac
